version: '3'
volumes:
  unuse:
services:
  docker-test: &app_base
    env_file: .env
    image: 709358053306.dkr.ecr.ap-northeast-1.amazonaws.com/docker_test:latest
    build: .
    ports:
      - "3000:3000"
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "ap-northeast-1"
        awslogs-group: "develop"
        awslogs-stream-prefix: "docker-test"
    environment:
      RAILS_MASTER_KEY: 910ba316a6467ce69af7110f966e610d
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "ON"
      APP_DATABASE_USER: docker_test
      APP_DATABASE_PASSWORD: testtest
      APP_DATABASE_HOST: docker-test.c5xfubdjquij.ap-northeast-1.rds.amazonaws.com
      APP_DATABASE_NAME: docker_test
    command: /bin/sh -c 'rm -f /docker_test/tmp/pids/server.pid && rails s -p 3000 -b 0.0.0.0 && rails assets:precompile'
  spring:
    <<: *app_base
    ports: []
    command: spring server
    stdin_open: true
    tty: true
    pid: host
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "ap-northeast-1"
        awslogs-group: "develop"
        awslogs-stream-prefix: "spring"
    environment:
      SPRING_SOCKET: /tmp/spring/spring.sock
      APP_DATABASE_USER: docker_test
      APP_DATABASE_PASSWORD: testtest
      APP_DATABASE_HOST: docker-test.c5xfubdjquij.ap-northeast-1.rds.amazonaws.com
      APP_DATABASE_NAME: docker_test